"""empty message

Revision ID: b9a5196cf7d3
Revises: c701d456a756
Create Date: 2022-12-22 09:50:17.163566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9a5196cf7d3'
down_revision = 'c701d456a756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_tourist_spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('add_favorite_id', sa.Integer(), nullable=True),
    sa.Column('spot_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['spot_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorite_tourist_Spots')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_tourist_Spots',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('add_favorite_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorite_tourist_spots')
    # ### end Alembic commands ###
